=== rarrington3/LRS/raml/api/v1/reviews/reviewanswer.schema.json
{
    "id": "http://LRS/ReviewAnswer",
    "type": "object",
    "$schema": "http://json-schema.org/draft-03/schema",
    "required": ["answerId", "reviewLevelId", "questionId", "qaTreeId"],
    "additionalProperties": false,
    "properties": {        
        "answerId": {
            "description": "The unique answer ID that can be used to update the answer",
            "type": "string"
        },
        "reviewLevelId": {
            "description": "The answer ID to a question for a specific loan review level",
            "type": "string"
        },
        "questionId": {
            "description": "The ID to the question this answer is for",
            "type": "string"
        },
        "qaTreeId": {
            "description": "The qa tree ID related to this review",
            "type": "string"
        },
        "answers": {
            "description": "The actual answer detail(s) to the qustion (e.g. [{code: 'Yes', description: 'Yes'}], or for a multiple choice: [{code:'1', description: 'Standard Employment'}, {code:'3', description:'Part-time and Seasonal Employment'}])",
            "type": "array",
            "items": {
                "$ref": "CommonDetail"
            }
        }
    }
}

=== rarrington3/LRS/raml/api/v1/reviews/reviewanswer.example.json
{
    "answerId": "19fb1e4b-0bcb-4157-9537-16c1d3c4d7e9",
    "reviewLevelId": "3397d4a9-ad51-497c-a545-8a983d7edf52",
    "questionId": "5b3386a4-3e48-473d-9df2-5cd83a549834",
    "qaTreeId": "BEE76DDC-5907-435C-80D1-45F894F7BD3C",
    "answers": [
        {
            "code": "Yes",
            "description": "Yes"
        }
    ]
}

=== rarrington3/LRS/raml/api/v1/reviews/reviewanswer-collection.example.json
[
    {
        "answerId": "19fb1e4b-0bcb-4157-9537-16c1d3c4d7e9",
        "reviewLevelId": "3397d4a9-ad51-497c-a545-8a983d7edf52",
        "questionId": "5b3386a4-3e48-473d-9df2-5cd83a549834",
        "qaTreeId": "BEE76DDC-5907-435C-80D1-45F894F7BD3C",
        "answers": [
            {
                "code": "Yes",
                "description": "Yes"
            }
        ]
    },
    {
        "answerId": "4c1f58fd-d391-4b43-9206-a38a898bd8c1",
        "reviewLevelId": "cb35a34e-5c6a-4494-bcc1-18eb8ffcdf2b",
        "questionId": "1cb871a9-1c80-4064-81f9-6168df284bba",
        "qaTreeId": "BEE76DDC-5907-435C-80D1-45F894F7BD3C",
        "answers": [
            {
                "code": "Yes",
                "description": "Yes"
            }
        ]
    },
    {
        "answerId": "a56365c4-d683-4c91-9805-81687fa34f89",
        "reviewLevelId": "ccb5a34e-5c6a-4494-bcc1-18eb8ffcdf2b",
        "questionId": "67717fc6-f7ec-4044-93aa-f9d3587a1315",
        "qaTreeId": "BEE76DDC-5907-435C-80D1-45F894F7BD3C",
        "answers": [
            {
                "code": "Yes",
                "description": "Yes"
            }
        ]
  },
  {
        "answerId": "02544d5a-61a0-4e42-b2e0-aba19dd3b003",
        "reviewLevelId": "c3c5a34e-5c6a-4494-bcc1-18eb8ffcdf2b",
        "questionId": "cb6a46bd-a6f0-46e8-b7ac-5d84b49fd8af",
        "qaTreeId": "BEE76DDC-5907-435C-80D1-45F894F7BD3C",
        "answers": [
            {
                "code": "No",
                "description": "No"
            }
        ]
  }
]
