=== rarrington3/LRS/raml/api/v1/reviews/reviewfinding.schema.json
{
    "id": "http://LRS/ReviewFinding",
    "type": "object",
    "$schema": "http://json-schema.org/draft-03/schema",
    "required": [
        "findingId",
        "reviewLevelId"
    ],
    "additionalProperties": false,
    "properties": {
        "findingId": {
            "description": "The finding ID.",
            "type": "string"
        },
        "reviewLevelId": {
            "description": "The review level ID.",
            "type": "string"
        },
        "originalReviewLevelId": {
            "description": "The review level ID when the finding was created.",
            "type": "string"
        },
        "defectAreaCode": {
            "description": "Defect code that is involved in this review (based on the review type).  The display text of this code can be retrieved from the 'defectAreaDictionary' service.",
            "type": "string"
        },
        "questionIds": {
            "description": "A collection of question IDs that this finding is related to.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "selectedSourceCode": {
            "description": "The source code that was selected for this finding. The source code will relate to a source dictionary ojbect (e.g. 'Standard Employment', 'Maximum Mortgage Amount', etc.)",
            "type": "string"
        },
        "selectedCauseCode": {
            "description": "The cause code that was selected for this finding. The cause code will relate to a cause dictionary ojbect (e.g. 'Amount not supported by documentation', 'Amounts cannot be confirmed', etc.)",
            "type": "string"
        },
        "selectedTierCode": {
            "description": "The tier (severity) that was selected for this finding.",
            "type": "string"
        },
        "commentToLender": {
            "description": "A note to the lender for this finding.",
            "type": "string"
        },
        "ratingCode": {
            "description": "The rating given to this finding which is based on defect area, source, cause, and severity tier. Known codes: 'C' = Conforming, 'D' = Deficient, 'M' = Mitigated, 'R' = Remediated, 'U' = Unacceptable. Use the ratingcodedictionary API to translate code to description.",
            "type": "string"
        },
        "lenderResponseDate": {
            "description": "The date when the lender responded to this finding",
            "type": "string",
            "format": "date"
        },
        "lenderResponderName": {
            "description": "The name of the user (lender) that responded to this finding. (e.g. 'John Franklin')",
            "type": "string"
        },
        "lenderResponseComment": {
            "description": "The lender's response to this finding.",
            "type": "string"
        },
        "lenderResponseDocuments": {
            "description": "A collection of files that were uploaded as response documents",
            "type": "array",
            "items": {
                "$ref": "Document"
            }
        },
        "lenderResponseExpiredDate": {
            "description": "The date if the lender request response was expired",
            "type": "string",
            "format": "date"
        },
        "reviewerResponseMitigated": {
            "description": "The reviewer is satisfied with the lender response. When this is set to true, the services will update the ratingCode to 'M'",
            "type": "boolean"
        },
        "reviewerResponseRemediated": {
            "description": "the reviewer has decided that the lenders response is an acceptable remediation to the finding and can capture an amount. When this is set, the services will update the ratingCode to 'R'",
            "$ref": "RemediationResponse"
        },
        "reviewerResponseAdjusted": {
            "description": "The reviewer is making an adjustment to the fining. Possible values will be 'C', '1', '2', '3', '4'. The numbers here represent a new selectedTierCode where as the 'C' represents 'Conforming' no matter the current severity tier. The services will use the suggestion and update the ratingCode and selectedTierCode",
            "type": "string"
        },
        "isAdhoc": {
            "description": "If this finding was created as an adhoc finding, this flag will be set to true.",
            "type": "boolean"
        },
        "nameFirst": {
            "description": "The forename of the reviewer.",
            "type": "string"
        },
        "nameLast": {
            "description": "The family name of the reviewer.",
            "type": "string"
        },
        "lastUpdated": {
            "description": "Date and time when the note was last updated (or created if no updates).",
            "type": "string",
            "format": "date-time"
        }
    }
}

=== rarrington3/LRS/raml/api/v1/reviews/reviewfinding.example.json
{
    "findingId": "A93C4BDE-71AF-4579-B6E6-C6D5515A2C51",
    "reviewLevelId": "1722D21A-D282-4655-912D-C360185F2A05",
    "originalReviewLevelId": "1722D21A-D282-4655-912D-C360185F2A05",
    "defectAreaCode": "BA",
    "questionIds": [
        "8C90DC5F-9BA9-42CC-B601-9B7C1CE071A2"
    ],
    "selectedSourceCode": "2",
    "selectedCauseCode": "B",
    "selectedTierCode": "3",
    "commentToLender": "We found another issue with the loan. This is some notes to the lender.",
    "ratingCode": "U",
    "lenderResponseComment": "Sample response to FHA from the lender about this finding/defect and an explandation.",
    "lenderResponseDocuments": [
        { "documentId": "1AA38E66-75F2-4678-8AC3-52A005CF5745", "documentType": "RESP", "fileName": "borrower_w2.jpg" },
        { "documentId": "1AA38E66-75F2-4678-8AC3-52A005CF5746", "documentType": "RESP", "fileName": "borrowerId.pdf" },
        { "documentId": "1AA38E66-75F2-4678-8AC3-52A005CF5747", "documentType": "RESP", "fileName": "mortgage_papers.pdf" }
    ],
    "isAdhoc": false
}

=== rarrington3/LRS/raml/api/v1/reviews/lenderfindingupdate.example.json
{
    "findingId": "A93C4BDE-71AF-4579-B6E6-C6D5515A2C51",
    "reviewLevelId": "1722D21A-D282-4655-912D-C360185F2A05",
    "ratingCode": "U",
    "defectAreaCode": "BA",
    "selectedSourceCode": "1",
    "selectedCauseCode": "B",
    "selectedTierCode": "1",
    "lenderResponseComment": "Sample response to FHA from the lender about this finding/defect and an explandation.",
    "lenderResponseDocuments": [
        { "documentId": "1AA38E66-75F2-4678-8AC3-52A005CF5745", "documentType": "RESP", "fileName": "borrower_w2.jpg" },
        { "documentId": "1AA38E66-75F2-4678-8AC3-52A005CF5746", "documentType": "RESP", "fileName": "borrowerId.pdf" },
        { "documentId": "1AA38E66-75F2-4678-8AC3-52A005CF5747", "documentType": "RESP", "fileName": "mortgage_papers.pdf" }
    ]
}

=== rarrington3/LRS/raml/api/v1/reviews/reviewfinding-collection.example.json
[
    {
        "findingId": "A93C4BDE-71AF-4579-B6E6-C6D5515A2C51",
        "reviewLevelId": "d2f957de-83e8-45a6-a384-458603727fc7",
        "originalReviewLevelId": "d2f957de-83e8-45a6-a384-458603727fc7",
        "defectAreaCode": "BA",
        "questionIds": [
            "8C90DC5F-9BA9-42CC-B601-9B7C1CE071A2",
            "67717fc6-f7ec-4044-93aa-f9d3587a1315"
        ],
        "selectedSourceCode": "1",
        "selectedCauseCode": "B",
        "selectedTierCode": "1",
        "commentToLender": "We found an issue with the loan. This is some notes to the lender.",
        "ratingCode": "U",
        "lenderResponseDate": "2016-08-01",
        "lenderResponderName": "Banker, Fred",
        "lenderResponseComment": "Sample response to FHA from the lender about this finding/defect and an explandation.",
        "lenderResponseDocuments": [
            { "documentId": "1AA38E66-75F2-4678-8AC3-52A005CF5745", "documentType": "RESP", "fileName": "borrower_w2.jpg" },
            { "documentId": "1AA38E66-75F2-4678-8AC3-52A005CF5746", "documentType": "RESP", "fileName": "borrowerId.pdf" },
            { "documentId": "1AA38E66-75F2-4678-8AC3-52A005CF5747", "documentType": "RESP", "fileName": "mortgage_papers.pdf" }
        ],
        "isAdhoc": true
    },
    {
        "findingId": "311D367F-2C0B-4A4D-9493-306E8CF5CEBA",
        "reviewLevelId": "228ce36cb-a8f1-481c-bb93-609fd0c553d6",
        "originalReviewLevelId": "d2f957de-83e8-45a6-a384-458603727fc7",
        "defectAreaCode": "BA",
        "questionIds": [
            "cb6a46bd-a6f0-46e8-b7ac-5d84b49fd8af",
            "67717fc6-f7ec-4044-93aa-f9d3587a1315"
        ],
        "selectedSourceCode": "1",
        "selectedCauseCode": "C",
        "selectedTierCode": "1",
        "commentToLender": "We found another issue with the loan. This is some more notes to the lender.",
        "ratingCode": "U",
        "lenderResponseDate": "2016-08-03",
        "lenderResponderName": "Banker, Fred",
        "lenderResponseComment": "Another sample response to FHA from the lender about this finding/defect and an explandation.",
        "isAdhoc": false
    },
    {
        "findingId": "B92CBD7F-B3F3-4853-A86E-C642CB58E633",
        "reviewLevelId": "230ce36cb-a8f1-481c-bb93-609fd0c553d6",
        "originalReviewLevelId": "230ce36cb-a8f1-481c-bb93-609fd0c553d6",
        "defectAreaCode": "BA",
        "questionIds": [
            "6C90DC5F-9BA9-42CC-B601-9B7C1CE071A9"
        ],
        "selectedSourceCode": "1",
        "selectedCauseCode": "B",
        "selectedTierCode": "1",
        "ratingCode": "U",
        "lenderResponseDocuments": [
          { "documentId": "1AA38E66-75F2-4678-8AC3-52A005CF5745", "documentType": "RESP", "fileName": "borrower_w2.jpg" },
          { "documentId": "1AA38E66-75F2-4678-8AC3-52A005CF5746", "documentType": "RESP", "fileName": "borrowerId.pdf" },
          { "documentId": "1AA38E66-75F2-4678-8AC3-52A005CF5747", "documentType": "RESP", "fileName": "mortgage_papers.pdf" }
        ]
    },
    {
        "findingId": "AAAE2CBD7F-B3F3-4853-A86E-C642CB58E633",
        "reviewLevelId": "230ce36cb-a8f1-481c-bb93-609fd0c553d6",
        "defectAreaCode": "PE",
        "questionIds": [
            "6C90DC5F-9BA9-42CC-B601-9B7C1CE071A9"
        ],
        "selectedSourceCode": "1",
        "selectedCauseCode": "B",
        "selectedTierCode": "1",
        "ratingCode": "U",
        "lenderResponseDocuments": [
          { "documentId": "1AA38E66-75F2-4678-8AC3-52A005CF5745", "documentType": "RESP", "fileName": "borrower_w2.jpg" },
          { "documentId": "1AA38E66-75F2-4678-8AC3-52A005CF5746", "documentType": "RESP", "fileName": "borrowerId.pdf" },
          { "documentId": "1AA38E66-75F2-4678-8AC3-52A005CF5747", "documentType": "RESP", "fileName": "mortgage_papers.pdf" }
        ],
        "reviewerResponseAdjusted": "4"
    },
    {
        "findingId": "FEFCBD7F-B3F3-4853-A86E-C642CB58E633",
        "reviewLevelId": "230ce36cb-a8f1-481c-bb93-609fd0c553d6",
        "defectAreaCode": "PA",
        "questionIds": [
            "6C90DC5F-9BA9-42CC-B601-9B7C1CE071A9"
        ],
        "selectedSourceCode": "1",
        "selectedCauseCode": "B",
        "selectedTierCode": "1",
        "ratingCode": "U",
        "lenderResponseDocuments": [
          { "documentId": "1AA38E66-75F2-4678-8AC3-52A005CF5745", "documentType": "RESP", "fileName": "borrower_w2.jpg" },
          { "documentId": "1AA38E66-75F2-4678-8AC3-52A005CF5746", "documentType": "RESP", "fileName": "borrowerId.pdf" },
          { "documentId": "1AA38E66-75F2-4678-8AC3-52A005CF5747", "documentType": "RESP", "fileName": "mortgage_papers.pdf" }
        ],
        "reviewerResponseRemediated":  {
            "remediationTypeCode": "BR",
            "remediationAmount": 4500.00
        }
    },
    {
        "findingId": "CTFCBD7F-B3F3-4853-A86E-C642CB58E633",
        "reviewLevelId": "230ce36cb-a8f1-481c-bb93-609fd0c553d6",
        "defectAreaCode": "ME",
        "questionIds": [
            "6C90DC5F-9BA9-42CC-B601-9B7C1CE071A9"
        ],
        "selectedSourceCode": "1",
        "selectedCauseCode": "B",
        "selectedTierCode": "1",
        "ratingCode": "U",
        "lenderResponseDocuments": [
          { "documentId": "1AA38E66-75F2-4678-8AC3-52A005CF5745", "documentType": "RESP", "fileName": "borrower_w2.jpg" },
          { "documentId": "1AA38E66-75F2-4678-8AC3-52A005CF5746", "documentType": "RESP", "fileName": "borrowerId.pdf" },
          { "documentId": "1AA38E66-75F2-4678-8AC3-52A005CF5747", "documentType": "RESP", "fileName": "mortgage_papers.pdf" }
        ],
        "reviewerResponseMitigated": true
    },
    {
        "findingId": "0EFCBD7F-B3F3-4853-A86E-C642CB58E633",
        "reviewLevelId": "230ce36cb-a8f1-481c-bb93-609fd0c553d6",
        "defectAreaCode": "BA",
        "questionIds": [
            "6C90DC5F-9BA9-42CC-B601-9B7C1CE071A9"
        ],
        "selectedSourceCode": "1",
        "selectedCauseCode": "B",
        "selectedTierCode": "1",
        "ratingCode": "U",
        "lenderResponseDocuments": [
          { "documentId": "1AA38E66-75F2-4678-8AC3-52A005CF5745", "documentType": "RESP", "fileName": "borrower_w2.jpg" },
          { "documentId": "1AA38E66-75F2-4678-8AC3-52A005CF5746", "documentType": "RESP", "fileName": "borrowerId.pdf" },
          { "documentId": "1AA38E66-75F2-4678-8AC3-52A005CF5747", "documentType": "RESP", "fileName": "mortgage_papers.pdf" }
        ],
        "reviewerResponseMitigated": true,
        "isAdhoc": false
    },
    {
        "findingId": "4E90639E-FC7A-415E-A011-59AD8E58D058",
        "reviewLevelId": "228ce36cb-a8f1-481c-bb93-609fd0c553d6",
        "originalReviewLevelId": "d2f957de-83e8-45a6-a384-458603727fc7",
        "defectAreaCode": "BA",
        "selectedSourceCode": "1",
        "selectedCauseCode": "B",
        "selectedTierCode": "1",
        "commentToLender": "We found another issue with the loan. This is some more notes to the lender. This finding wasn't found because of a question, rather an adhoc.",
        "ratingCode": "U",
        "isAdhoc": true
    }

]
