=== rarrington3/LRS/raml/api/v1/reviews/reviewfield.schema.json
{
    "id": "http://LRS/ReviewField",
    "type": "object",
    "$schema": "http://json-schema.org/draft-03/schema",
    "required": ["fieldId", "order", "name", "type", "value", "valuesAtEndorsement", "valuesAtUnderwriting", "isEditable"],
    "additionalProperties": false,
    "properties": {
        "fieldId": {
            "description": "The unique identifier for this field",
            "type": "string"
        },
        "order": {
            "description": "Sort order of this field relative to others displayed in the same panel",
            "type": "integer"
        },
        "type": {
            "description": "What type of UI element is used to display this?  Valid values are 'date', 'boolean', 'integer', 'number', 'currency', and 'select', and 'multiselect'",
            "type": "string"
        },
        "conditionsToDisplay" : {
            "description": "A collection of condition objects that the UI will use to determine if this field should be displayed (in any defect area or loan summary view).  If no conditions are included the question is displayed.",
            "type": "array",
            "items": {
                "$ref": "ReviewCondition"
            }
        },
        "loanAttributeGroup": {
            "description": "Which section of the loan attributes screen this should be displayed in. Valid values are 'Loan', 'Property', and 'Borrower'. If NULL the field should not be displayed in the loan summary",
            "type": "string"
        },
        "displayInDefectAreas": {
            "description": "Which defect areas, if any, should display this field in their sidebar.  Values are the defect area codes (example: LA)",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "selectChoices": {
            "description": "If type=select or multiselect, this is the array of options for the user to choose from",
            "type": "array",
            "items": {
                "$ref": "CommonDetail"
            }
        },
        "minValue": {
            "description": "If type=integer, number, or currency this is the minimum allowed value",
            "type":"number"
        },
        "maxValue": {
            "description": "If type=integer, number, or currency this is the maximum allowed value",
            "type":"number"
        },
        "name": {
            "description": "The display name of the field (The DB refers to this as FIELD_NAME)",
            "type": "string"
        },
        "value": {
            "description": "The editable value for this field which is used to determine which questions are displayed to the user",
            "type": "string"
        },
        "isEditable": {
            "description": "Is this field editable",
            "type": "boolean"
        },
        "valuesAtEndorsement": {
            "description": "The values of this field at the time of endorsement (as reported by other systems).  Read-only. For most cases this will be a collection of one value, but in the case of multiple select it will be multiple values.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "valuesAtUnderwriting": {
            "description": "The values of this field at the time of underwriting (as reported by other systems).  Read-only. For most cases this will be a collection of one value, but in the case of multiple select it will be multiple values.",
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    }
}

=== rarrington3/LRS/raml/api/v1/reviews/reviewfield.example.json
{
    "fieldId": "LIV_UNITS",
    "order": 1,
    "conditionsToDisplay": [
        {
            "conditionId": "9b1c1905-ce56-456e-a3cc-1e1f671fd058",
            "entityName": "123",
            "fieldName": "LOAN_TYPE",
            "operator": "in",
            "comparisonValues": [
                "HECM",
                "Refinance",
                "Purchase"
            ]
        }
    ],
    "name": "Living Units",
    "value": "2",
    "valuesAtUnderwriting": [
        "1"
    ],
    "valuesAtEndorsement": [
        "2"
    ],
    "type": "integer",
    "loanAttributeGroup": "Property",
    "isEditable": false
}

=== rarrington3/LRS/raml/api/v1/reviews/reviewfield-collection.example.json
[
    {
        "fieldId": "Living Units",
        "order": 0,
        "conditionsToDisplay": [
            {
                "conditionId": "9b1c1905-ce56-456e-a3cc-1e1f671fd058",
                "entityName": "123",
                "fieldName": "LOAN_TYPE",
                "operator": "in",
                "comparisonValues": [
                    "HECM",
                    "Refinance",
                    "Purchase"
                ]
            }
        ],
        "name": "Living Units",
        "value": "1",
        "valuesAtUnderwriting": [
            "1"
        ],
        "valuesAtEndorsement": [
            "2"
        ],
        "type": "integer",
        "loanAttributeGroup": "Property",
        "isEditable": false
    },
    {
        "fieldId": "Loan to Value Ratio - New",
        "order": 1,
        "isEditable": false,
        "conditionsToDisplay": [
            {
                "conditionId": "9b1c1905-ce56-456e-a3cc-1e1f671fd058",
                "entityName": "123",
                "fieldName": "LOAN_TYPE",
                "operator": "in",
                "comparisonValues": [
                    "HECM",
                    "Refinance",
                    "Purchase"
                ]
            }
        ],
        "name": "Loan to Value Ratio - New",
        "value": "90.01",
        "valuesAtUnderwriting": [
            "90.01"
        ],
        "valuesAtEndorsement": [
            "90.01"
        ],
        "type": "number",
        "loanAttributeGroup": "Property",
        "displayInDefectAreas": [
            "LA"
        ]
    },
    {
        "fieldId": "Gift Letter Amount",
        "order": 2,
        "isEditable": false,
        "conditionsToDisplay": [
            {
                "conditionId": "9b1c1905-ce56-456e-a3cc-1e1f671fd058",
                "entityName": "123",
                "fieldName": "LOAN_TYPE",
                "operator": "in",
                "comparisonValues": [
                    "HECM",
                    "Refinance",
                    "Purchase"
                ]
            }
        ],
        "name": "Gift Letter Amount",
        "value": "150",
        "valuesAtUnderwriting": [
            "150"
        ],
        "valuesAtEndorsement": [
            "150"
        ],
        "type": "currency",
        "loanAttributeGroup": "Borrower",
        "displayInDefectAreas": [
            "LA",
            "PE"
        ]
    },
    {
        "fieldId": "SOA_CD",
        "order": 3,
        "isEditable": false,
        "conditionsToDisplay": [
            {
                "conditionId": "9b1c1905-ce56-456e-a3cc-1e1f671fd058",
                "entityName": "123",
                "fieldName": "LOAN_TYPE",
                "operator": "in",
                "comparisonValues": [
                    "Purchase"
                ]
            }
        ],
        "name": "SOA Code - Display if LOAN_TYPE has Purchase",
        "value": "211",
        "valuesAtUnderwriting": [
            "2016-07-16T19:20+01:00"
        ],
        "valuesAtEndorsement": [
            "2016-07-16T19:20+01:00"
        ],
        "type": "date",
        "loanAttributeGroup": "Loan",
        "displayInDefectAreas": [
            "BE"
        ]
    },
    {
        "fieldId": "LOAN_TYPE",
        "order": 7,
        "isEditable": false,
        "name": "LOAN_TYPE Multiselect",
        "value": "Refinance,Purchase,HECM",
        "valuesAtUnderwriting": [
            "HECM"
        ],
        "valuesAtEndorsement": [
            "HECM"
        ],
        "type": "multiselect",
        "selectChoices": [
            {
                "code": "HECM",
                "description": "HECM"
            },
            {
                "code": "Refinance",
                "description": "Refinance"
            },
            {
                "code": "Purchase",
                "description": "Purchase"
            }
        ],
        "loanAttributeGroup": "Loan",
        "displayInDefectAreas": [
            "LA",
            "BE"
        ]
    },
    {
        "fieldId": "Refinance Code",
        "order": 4,
        "isEditable": false,
        "conditionsToDisplay": [
            {
                "conditionId": "9b1c1905-ce56-456e-a3cc-1e1f671fd058",
                "entityName": "123",
                "fieldName": "RFNC_CDRADIO",
                "operator": "=",
                "comparisonValues": [
                    "Yes"
                ]
            }
        ],
        "name": "Refinance Code",
        "value": "A",
        "valuesAtUnderwriting": [
            "A"
        ],
        "valuesAtEndorsement": [
            "A"
        ],
        "type": "select",
        "selectChoices": [
            {
                "code": "A",
                "description": "A"
            },
            {
                "code": "B",
                "description": "B"
            },
            {
                "code": "C",
                "description": "C"
            }
        ],
        "loanAttributeGroup": "Loan",
        "displayInDefectAreas": [
            "LA",
            "BE"
        ]
    },
    {
        "fieldId": "Refinance Code Radio",
        "order": 5,
        "isEditable": false,
        "name": "Refinance Code Radio",
        "value": "No",
        "valuesAtUnderwriting": [
            "A"
        ],
        "valuesAtEndorsement": [
            "A"
        ],
        "type": "boolean",
        "selectChoices": [],
        "loanAttributeGroup": "Loan",
        "displayInDefectAreas": [
            "LA",
            "BE"
        ]
    },
    {
        "fieldId": "RFNC_CDRADIO_2",
        "order": 5,
        "isEditable": false,
        "name": "RFNC_CDRADIO Radio 2",
        "value": "No",
        "valuesAtUnderwriting": [
            "A"
        ],
        "valuesAtEndorsement": [
            "A"
        ],
        "type": "boolean",
        "selectChoices": [],
        "loanAttributeGroup": "Loan",
        "displayInDefectAreas": [
            "LA",
            "BE"
        ]
    },
    {
        "fieldId": "Refinance Code Multi",
        "order": 6,
        "isEditable": false,
        "name": "Refinance Code Multiselect",
        "value": "B",
        "valuesAtUnderwriting": [
            "A"
        ],
        "valuesAtEndorsement": [
            "A"
        ],
        "type": "multiselect",
        "selectChoices": [
            {
                "code": "A",
                "description": "A"
            },
            {
                "code": "B",
                "description": "B"
            },
            {
                "code": "C",
                "description": "C"
            }
        ],
        "loanAttributeGroup": "Loan",
        "displayInDefectAreas": [
            "LA",
            "BE"
        ]
    },
    {
        "order": 7,
        "isEditable": false,
        "fieldId": "Refinance Code",
        "name": "Refinance Code Static",
        "value": "82323",
        "valuesAtUnderwriting": [
            "A"
        ],
        "valuesAtEndorsement": [
            "A"
        ],
        "type": "static",
        "selectChoices": [],
        "displayInDefectAreas": [
            "LA"
        ]
    },
    {
        "fieldId": "SOA_CDD",
        "order": 8,
        "name": "SOA Code",
        "value": "213",
        "isEditable": false,
        "valuesAtUnderwriting": [
            "3211"
        ],
        "valuesAtEndorsement": [
            "1211"
        ],
        "type": "integer",
        "displayInDefectAreas": [
            "BE"
        ]
    }
]
