=== rarrington3/LRS/raml/api/v1/reviews/reviewquestion.schema.json
{
    "id": "http://LRS/ReviewQuestion",
    "type": "object",
    "$schema": "http://json-schema.org/draft-03/schema",
    "required": [
        "questionId",
        "questionReference",
        "order",
        "questionText",
        "answerType",
        "potentialAnswers"
    ],
    "additionalProperties": false,
    "properties": {
        "questionId": {
            "description": "The question ID.",
            "type": "string"
        },
        "questionNumber": {
            "description": "The question number.",
            "type": "string"
        },
        "questionReference": {
            "description": "The question unique reference string for this question that is a combination of questionNumber and defect area (e.g. 'BA.002'). NOTE: This is generated by services when question is created.",
            "type": "string"
        },
        "parentQuestionId": {
            "description": "The question ID of this question's parent (if this question is a child)",
            "type": "string"
        },
        "parentQuestionConditionAnswers": {
            "description": "Collection of answers which will be used to test if this question can be displayed if this question is a child (i.e. has a parentQuestionId). Each answer here will be checked against the parent question's answer with an OR condition. If there are multiple answers on the parent question, this question will display if at least one answer matches at least one parent question answer (i.e. 'intersects').",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "order": {
            "description": "The order in which this question needs to be displayed",
            "type": "integer"
        },
        "questionText": {
            "description": "The actual question text to display.",
            "type": "string"
        },
        "answerType": {
            "description": "The type of answer that the user will be able to select. (e.g. 'single' or 'multiple')",
            "type": "string"
        },
        "potentialAnswers": {
            "description": "Used to supply potential answers for this question (e.g. For answerType of 'single': [Yes, No] or [Yes, No, NA], for answerType of 'multiple': [1, 2, 3, ...]). Note that this uses the CommonDetail object which provides a code and description for each potentialAnswer. The description will be used for display (e.g. 'Standard Employment' or 'Part-time and Seasonal Employment'), the code will be used by the database and services (e.g. '1', '2').",
            "type": "array",
            "items": {
                "$ref": "CommonDetail"
            }
        },
        "answerToTriggerFinding": {
            "description": "If the user selects this answer code, a finding will be triggered. NOTE: This relates to the answerDetail.code",
            "type": "string"
        },
        "conditionsToDisplay" : {
            "description": "A collection of condition objects that the UI will use to determine if this question should be displayed. Conditions will relate to loan/defect summary field info. If no conditions are included the question is displayed. NOTE: if this question includes a parentQuestionId and parentQuestionConditionAnswers, that will also be used to display the question.",
            "type": "array",
            "items": {
                "$ref": "ReviewCondition"
            }
        },
        "allowableSourceCodes": {
            "description": "A collection of source Codes that could be selected when logging a finding. The source ID will relate to a source dictionary ojbect (e.g. 'Standard Employment', 'Maximum Mortgage Amount', etc.)",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "allowableCauseCodes": {
            "description": "A collection of cause Codes that could be selected when logging a finding. The cause ID will relate to a cause dictionary ojbect (e.g. 'Amount not supported by documentation', 'Amounts cannot be confirmed', etc.)",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "allowedSeverityCodes": {
            "description": "A collection of severity tier Codes that could be selected when logging a finding.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "questions": {
            "description": "Collection of qa model questions for this question in the defect area.",
            "type": "array",
            "items": {
                "$ref": "ReviewQuestion"
            }
        }
    }
}

=== rarrington3/LRS/raml/api/v1/reviews/reviewquestion-collection.example.json
[
    {
        "questionId": "5b3386a4-3e48-473d-9df2-5cd83a549834",
        "questionNumber": "147",
        "questionReference": "BA.147",
        "order": 1,
        "questionText": "Was an acceptable Gift Letter provided and consistent with other documents in the file?",
        "answerType": "Single",
        "potentialAnswers": [
            {
                "code": "Yes",
                "description": "Yes"
            },
            {
                "code": "No",
                "description": "No"
            }
        ],
        "answerToTriggerFinding": "No",
        "conditionsToDisplay": [
            {
                "conditionId": "14770ac1-f88d-4b23-bf4f-0206b9c737ff",
                "entityName": "123",
                "fieldName": "GIFT_LTR_AMT",
                "operator": ">",
                "comparisonValues": [
                    "0"
                ]
            }
        ],
        "allowableSourceCodes": [
            "1",
            "3"
        ],
        "allowableCauseCodes": [
            "A",
            "B"
        ],
        "allowedSeverityCodes": [
            "1",
            "3",
            "4"
        ]
    },
    {
        "questionId": "1cb871a9-1c80-4064-81f9-6168df284bba",
        "questionNumber": "148",
        "questionReference": "BA.148",
        "order": 2,
        "questionText": "Were the Reserves Acceptable and not from a Gift??",
        "answerType": "Single",
        "potentialAnswers": [
            {
                "code": "Yes",
                "description": "Yes"
            },
            {
                "code": "No",
                "description": "No"
            }
        ],
        "answerToTriggerFinding": "No",
        "conditionsToDisplay": [
            {
                "conditionId": "14770ac1-f88d-4b23-bf4f-0206b9c737ff",
                "entityName": "123",
                "fieldName": "GIFT_LTR_AMT",
                "operator": ">",
                "comparisonValues": [
                    "0"
                ]
            },
            {
                "conditionId": "ca6faf57-a62a-42ea-8c2b-1f9bc56b547f",
                "entityName": "123",
                "fieldName": "LIV_UNITS",
                "operator": "<",
                "comparisonValues": [
                    "2"
                ]
            },
            {
                "conditionId": "4a7f0526-78f8-4f18-b31d-8d1a5ad141c2",
                "entityName": "123",
                "fieldName": "SOA_CD",
                "operator": "!=",
                "comparisonValues": [
                    "255"
                ]
            }
        ],
        "allowableSourceCodes": [
            "1",
            "3"
        ],
        "allowableCauseCodes": [
            "A",
            "B"
        ],
        "allowedSeverityCodes": [
            "1",
            "3",
            "4"
        ]
    },
    {
        "questionId": "3d7d4199-bc47-4968-aca0-7ec345947d38",
        "questionNumber": "149",
        "questionReference": "BA.149",
        "order": 3,
        "questionText": "Was real estate sold?",
        "answerType": "Single",
        "potentialAnswers": [
            {
                "code": "Yes",
                "description": "Yes"
            },
            {
                "code": "No",
                "description": "No"
            }
        ]
    },
    {
        "questionId": "929b529f-af29-4804-9f68-d98ceb727ef5",
        "questionNumber": "150",
        "questionReference": "BA.150",
        "parentQuestionId": "3d7d4199-bc47-4968-aca0-7ec345947d38",
        "parentQuestionConditionAnswers": [
            "Yes"
        ],
        "order": 4,
        "questionText": "Was the Closing Disclosure acceptable and provided?",
        "answerType": "Single",
        "potentialAnswers": [
            {
                "code": "Yes",
                "description": "Yes"
            },
            {
                "code": "No",
                "description": "No"
            }
        ],
        "answerToTriggerFinding": "No",
        "conditionsToDisplay": [
            {
                "conditionId": "0ac4e5da-65af-4053-9a52-5cb7400b30d9",
                "entityName": "123",
                "fieldName": "RFNC_CD",
                "operator": "!=",
                "comparisonValues": [
                    "S",
                    "H"
                ]
            }
        ],
        "allowableSourceCodes": [
            "1",
            "3"
        ],
        "allowableCauseCodes": [
            "A",
            "B"
        ],
        "allowedSeverityCodes": [
            "1",
            "3",
            "4"
        ]
    },
    {
        "questionId": "67717fc6-f7ec-4044-93aa-f9d3587a1315",
        "questionNumber": "151",
        "questionReference": "BA.151",
        "order": 5,
        "questionText": "Does a Depository account exist?",
        "answerType": "Single",
        "potentialAnswers": [
            {
                "code": "Yes",
                "description": "Yes"
            },
            {
                "code": "No",
                "description": "No"
            }
        ],
        "answerToTriggerFinding": "No",
        "allowableSourceCodes": [
          "1",
          "2",
          "3"
        ],
        "allowableCauseCodes": [
          "A",
          "B",
          "C"
        ],
        "allowedSeverityCodes": [
          "1",
          "3",
          "4"
      ]
    },
    {
        "questionId": "b2b83aac-6415-4334-97bb-90a89549d60f",
        "questionNumber": "152",
        "questionReference": "BA.152",
        "parentQuestionId": "67717fc6-f7ec-4044-93aa-f9d3587a1315",
        "parentQuestionConditionAnswers": [
            "Yes"
        ],
        "order": 6,
        "questionText": "Was a two month Average balance in the Depository Account provided?",
        "answerType": "Single",
        "potentialAnswers": [
            {
                "code": "Yes",
                "description": "Yes"
            },
            {
                "code": "No",
                "description": "No"
            }
        ],
        "answerToTriggerFinding": "No",
        "conditionsToDisplay": [
            {
                "conditionId": "14770ac1-f88d-4b23-bf4f-0206b9c737ff",
                "entityName": "123",
                "fieldName": "GIFT_LTR_AMT",
                "operator": ">",
                "comparisonValues": [
                    "0"
                ]
            }
        ],
        "allowableSourceCodes": [
            "1",
            "3"
        ],
        "allowableCauseCodes": [
            "A",
            "B"
        ],
        "allowedSeverityCodes": [
            "1",
            "3",
            "4"
        ]
    },
    {
        "questionId": "cb6a46bd-a6f0-46e8-b7ac-5d84b49fd8af",
        "questionNumber": "153",
        "questionReference": "BA.153",
        "parentQuestionId": "67717fc6-f7ec-4044-93aa-f9d3587a1315",
        "parentQuestionConditionAnswers": [
            "Yes"
        ],
        "order": 7,
        "questionText": "Another question that should only show up if the depository account existed?",
        "answerType": "Single",
        "potentialAnswers": [
            {
                "code": "Yes",
                "description": "Yes"
            },
            {
                "code": "No",
                "description": "No"
            }
        ],
        "answerToTriggerFinding": "No",
        "conditionsToDisplay": [
            {
                "conditionId": "14770ac1-f88d-4b23-bf4f-0206b9c737ff",
                "entityName": "123",
                "fieldName": "GIFT_LTR_AMT",
                "operator": ">",
                "comparisonValues": [
                    "0"
                ]
            }
        ],
        "allowableSourceCodes": [
            "1",
            "2"
        ],
        "allowableCauseCodes": [
            "A",
            "B"
        ],
        "allowedSeverityCodes": [
            "1",
            "3",
            "4"
        ]
    },
    {
        "questionId": "dca9ce1d-407e-424e-968d-a9cae8974cb8",
        "questionNumber": "154",
        "questionReference": "BA.154",
        "parentQuestionId": "67717fc6-f7ec-4044-93aa-f9d3587a1315",
        "parentQuestionConditionAnswers": [
            "No"
        ],
        "order": 8,
        "questionText": "Yet another question that should only show up if the depository didn't exist?",
        "answerType": "Single",
        "potentialAnswers": [
            {
                "code": "Yes",
                "description": "Yes"
            },
            {
                "code": "No",
                "description": "No"
            }
        ],
        "answerToTriggerFinding": "Yes",
        "conditionsToDisplay": [
            {
                "conditionId": "14770ac1-f88d-4b23-bf4f-0206b9c737ff",
                "entityName": "123",
                "fieldName": "GIFT_LTR_AMT",
                "operator": ">",
                "comparisonValues": [
                    "0"
                ]
            }
        ],
        "allowableSourceCodes": [
            "1"
        ],
        "allowableCauseCodes": [
            "A",
            "B"
        ],
        "allowedSeverityCodes": [
            "1",
            "2"
        ]
    },
    {
        "questionId": "dxe9ce1d-407e-424e-968d-a9cae8974cb8",
        "questionNumber": "155",
        "questionReference": "BA.155",
        "parentQuestionId": "dca9ce1d-407e-424e-968d-a9cae8974cb8",
        "parentQuestionConditionAnswers": [
            "No"
        ],
        "order": 9,
        "questionText": "Here is another question that should only show up if BA.154 is answered No?",
        "answerType": "Single",
        "potentialAnswers": [
            {
                "code": "Yes",
                "description": "Yes"
            },
            {
                "code": "No",
                "description": "No"
            }
