=== rarrington3/LRS/raml/api/v1/lenderselfreport/lenderSelfReport-schema.json
{
    "id": "http://LRS/LenderSelfReport",
    "type": "object",
    "$schema": "http://json-schema.org/draft-03/schema",
    "additionalProperties": false,
    "properties": {
        "reviewType": {
            "description": "The ID of the Review Type these loans have been selected for.",
            "type": "string"
        },
        "defectAreas": {
            "description": "A collection of IDs for applicable Defect Areas. Eg. 72CD9424-41C9-4C5D-996C-55241214EC26",
            "type": "array",
            "items": { "type": "string" }
        },
        "cases": {
            "description": "A collection of case numbers that need to be reviewed.",
            "type": "array",
            "items": { "type": "string" }
        },
        "isFraudDetected": {
            "decription": "A flag to signal that fraud has been detected on the submitted cases.",
            "type": "boolean"
        },
        "typesOfFraud": {
            "description": "A collection of IDs for applicable Fraud Types.",
            "type": "array",
            "items": { "type": "string" }
        },
        "fraudParticipants": {
            "description": "A collection of IDs for applicable Fraud Participants.",
            "type": "array",
            "items": { "type": "string" }
        },
        "descriptionOfFindings": {
            "description": "A short description of the findings which causes this case to need review.",
            "type": "string"
        },
        "descriptionOfCorrectiveActions": {
            "description": "A short description of the corrective actions being taken in this case.",
            "type": "string"
        },
        "isCoveredUnderSettlement": {
            "description": "A flag to signal that the given cases/loans are covered under settlement with HUD.",
            "type": "boolean"
        }
    }
}

=== rarrington3/LRS/raml/api/v1/lenderselfreport/lenderSelfReport-example.json
{
    "reviewType": "U",
    "defectAreas": [
        "72CD9424-41C9-4C5D-996C-55241214EC26",
        "81B55A27-C56E-4787-B152-604B80F44755",
        "9D7BBED9-0A67-4EDF-A79B-7A1C48B16C69",
        "BBF689FC-A866-42D6-96E7-DBE6F30B232D"
    ],
    "cases": [
        "063-7127265"
    ],
    "isFraudDetected": true,
    "typesOfFraud": [
        "FTwqer",
        "FTasdf"
    ],
    "fraudParticipants": [
        "FPqwer",
        "FPasdf"
    ],
    "descriptionOfFindings": "Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal that has evolved from generation X is on the runway heading towards a streamlined cloud solution.",
    "descriptionOfCorrectiveActions": "Corrective actions that have been takin",
    "isCoveredUnderSettlement": true
}
