=== rarrington3/LRS/raml/api/v1/exceptions/exception-schema.json
{
    "id": "http://LRS/Exception",
    "type": "object",
    "$schema": "http://json-schema.org/draft-03/schema",
    "required": ["exceptionId"],
    "additionalProperties": false,
    "properties": {
        "exceptionId": {
            "description": "The identifier of the object",
            "type": "string"
        },
        "caseNumber": {
            "description": "The case number for the loan.",
            "type": "string"
        },
        "borrowerName": {
            "description": "The legal name of the borrower.",
            "type": "string"
        },
        "lenderName": {
            "description": "The name of the lender who issues this loan.",
            "type": "string"
        },
        "selectionReasonCode": {
            "description": "The identifier of the object of the business rule that triggered the need to review this loan.  For example: 'Lender Monitoring', 'Random', 'Lender Self'",
            "type": "string"
        },
        "selectionReason": {
            "description": "Short name of the business rule that triggered the need to review this loan.  For example: 'Lender Monitoring', 'Random', 'Lender Self'",
            "type": "string"
        },
        "riskScore": {
            "description": "The numeric value representing the level of risk for this loan.",
            "type": "number"
        },
        "exceptionTypeCode": {
            "description": "The identifier of the exception that needs attention on this review.",
            "type": "string"
        },
        "exceptionType": {
            "description": "The short name of the exception that needs attention on this review.",
            "type": "string"
        },
        "daysOnList": {
            "description": "The number of days that this loan has been on the exception list.",
            "type": "number"
        },
        "assignedTo": {
            "description": "This is used to resolve assignment exceptions.",
            "type": "string"
        },
        "batchInfo": {
            "description": "This is used to resolve missing batch info exceptions.",
            "$ref": "Batch"
        },
        "reviewId": {
            "description": "The identifier of the review",
            "type": "string"
        },
        "currentReviewLevel": {
            "description": "The current review level object for this loan review. Each Review will have multiple review levels (i.e. 'passes') throughout it's life. Once this review level is completed, a new review level will be created and this one will be archived in the completedReviewLevels collection.",
            "$ref": "ReviewLevel"
        },
        "loanType": {
            "description": "The short name of the Loan Type that's being requested for review.",
            "type": "string"
        },
        "reviewLocationId": {
            "description": "The location where this distribution exception should be resolved to.",
            "type": "string"
        },
        "reviewType": {
            "description": "Review Type of this loan.",
            "type": "string"
        }
    }
}

=== rarrington3/LRS/raml/api/v1/exceptions/exception-example.json
{
    "exceptionId": "123",
    "caseNumber": "351-3576307",
    "borrowerName": "Robinson, Lawrence",
    "lenderName": "American Federal Savings",
    "selectionReasonCode": "SRasdf",
    "selectionReason": "Risk/Random",
    "riskScore": 67,
    "exceptionTypeCode": "ASSIGNMENT",
    "exceptionType": "Assignment",
    "daysOnList": 3,
    "reviewId": "F7F2B500-A743-40DA-9400-F490F751B21E",
    "currentReviewLevel": {
        "reviewLevelId": "d2f957de-83e8-45a6-a384-458603727fc7",
        "type": "Initial",
        "status": "Initial",
        "reviewerDateAssigned": "2016-07-20",
        "reviewerDateDue": "2016-07-28",
        "reviewLocationName": "Denver QAD",
        "dateRequestSentToLender": "2016-07-20",
        "dateResponseDueFromLender": "2016-07-28"
    },
    "loanType": "Reverse (HECM)",
    "reviewLocationId": "33e54129-ec1e-4cc6-b423-19f7ad1e70f1"
}

=== rarrington3/LRS/raml/api/v1/exceptions/exceptions-example.json
[
    {
        "exceptionId": "123qwer",
        "caseNumber": "351-3576307",
        "borrowerName": "Wolfeschlegelsteinhausenbergerdorff, Hubert Blaine",
        "lenderName": "American Federal Savings",
        "selectionReasonCode": "SRasdf",
        "selectionReason": "Risk/Random",
        "riskScore": 67,
        "exceptionTypeCode": "BATCH_DISTRIBUTION",
        "exceptionType": "Batch Distribution",
        "daysOnList": 3,
        "reviewId": "F7F2B500-A743-40DA-9400-F490F751B21E"
    },
    {
        "exceptionId": "456asdf",
        "caseNumber": "351-4988773",
        "borrowerName": "Riegel, Tiffany",
        "lenderName": "First National Bank of the United States of America",
        "selectionReasonCode": "SRtyui",
        "selectionReason": "Early Claim",
        "riskScore": 34,
        "exceptionTypeCode": "BATCH_ASSIGNMENT",
        "exceptionType": "Batch Assignment",
        "daysOnList": 11,
        "reviewId": "F7F2B500-A743-40DA-9400-F490F751B21E",
        "currentReviewLevel": {
            "reviewLevelId": "d2f957de-83e8-45a6-a384-458603727fc7",
            "type": "Initial",
            "status": "Initial",
            "reviewerDateAssigned": "2016-07-20",
            "reviewerDateDue": "2016-07-28",
            "reviewLocationName": "Denver QAD",
            "dateRequestSentToLender": "2016-07-20",
            "dateResponseDueFromLender": "2016-07-28"
        },
        "loanType": "Reverse (HECM)"
    },
    {
        "exceptionId": "789zxcv",
        "caseNumber": "351-1768306",
        "borrowerName": "Harkey, Evita",
        "lenderName": "Wells Fargo",
        "selectionReasonCode": "SRxcvb",
        "selectionReason": "Monitoring",
        "riskScore": 77,
        "exceptionTypeCode": "BINDER_REQUEST_ERROR",
        "exceptionType": "Binder Request Error",
        "daysOnList": 1,
        "reviewId": "F7F2B500-A743-40DA-9400-F490F751B21E",
        "currentReviewLevel": {
            "reviewLevelId": "d2f957de-83e8-45a6-a384-458603727fc7",
            "type": "Initial",
            "status": "Initial",
            "reviewerDateAssigned": "2016-07-20",
            "reviewerDateDue": "2016-07-28",
            "reviewLocationName": "Denver QAD",
            "dateRequestSentToLender": "2016-07-20",
            "dateResponseDueFromLender": "2016-07-28"
        },
        "loanType": "Reverse (HECM)"
    },
    {
        "exceptionId": "234wert",
        "caseNumber": "351-5198201",
        "borrowerName": "Coggin, Joseph",
        "lenderName": "Chase",
        "selectionReasonCode": "SRxcvb",
        "selectionReason": "Monitoring",
        "riskScore": 28,
        "exceptionTypeCode": "BINDER_REQUEST_PAST_DUE",
        "exceptionType": "Binder Request Past Due",
        "daysOnList": 6,
        "reviewId": "F7F2B500-A743-40DA-9400-F490F751B21E",
        "currentReviewLevel": {
            "reviewLevelId": "d2f957de-83e8-45a6-a384-458603727fc7",
            "type": "Initial",
            "status": "Initial",
            "reviewerDateAssigned": "2016-07-20",
            "reviewerDateDue": "2016-07-28",
            "reviewLocationName": "Denver QAD",
            "dateRequestSentToLender": "2016-07-20",
            "dateResponseDueFromLender": "2016-07-28"
        },
        "loanType": "Reverse (HECM)"
    },
    {
        "exceptionId": "345erty",
        "caseNumber": "351-1264427",
        "borrowerName": "Hodgins, Leonie",
        "lenderName": "Douglas County Bank",
        "selectionReasonCode": "SRvbnm",
        "selectionReason": "QC",
        "riskScore": 93,
        "exceptionTypeCode": "LOAN_SELECTION_DISTRIBUTION",
        "exceptionType": "Loan Selection Distribution",
        "daysOnList": 6,
        "reviewId": "F7F2B500-A743-40DA-9400-F490F751B21E"
    },
    {
        "exceptionId": "456fghjfh",
        "caseNumber": "351-9442769",
        "borrowerName": "Aguiniga, Marcel",
        "lenderName": "1st Bank",
        "selectionReasonCode": "SRsdfg",
        "selectionReason": "OIG Audit",
        "riskScore": 56,
        "exceptionTypeCode": "BINDER_REQUEST_PAST_DUE",
        "exceptionType": "Binder Request Past Due",
        "daysOnList": 8,
        "reviewId": "F7F2B500-A743-40DA-9400-F490F751B21E",
        "currentReviewLevel": {
            "reviewLevelId": "d2f957de-83e8-45a6-a384-458603727fc7",
            "type": "Initial",
            "status": "Initial",
            "reviewerDateAssigned": "2016-07-20",
            "reviewerDateDue": "2016-07-28",
            "reviewLocationName": "Denver QAD",
            "dateRequestSentToLender": "2016-07-20",
            "dateResponseDueFromLender": "2016-07-28"
        },
        "loanType": "Reverse (HECM)"
    },
    {
        "exceptionId": "456cvbncvb",
        "caseNumber": "351-0726552",
        "borrowerName": "Domenico, Marline",
        "lenderName": "American Federal Savings",
        "selectionReasonCode": "SRzxcv",
        "selectionReason": "EPD",
        "riskScore": 29,
        "exceptionTypeCode": "BINDER_REQUEST_PAST_DUE",
        "exceptionType": "Binder Request Past Due",
        "daysOnList": 17
    },
    {
        "exceptionId": "5423nnsdft4",
        "caseNumber": "351-0151464",
        "borrowerName": "Stickles, Fumiko",
        "lenderName": "First National Bank",
        "selectionReasonCode": "SRqwer",
        "selectionReason": "Test Case",
        "riskScore": 84,
        "exceptionTypeCode": "BATCH_ASSIGNMENT",
        "exceptionType": "Batch Assignment",
        "daysOnList": 2,
        "reviewId": "F7F2B500-A743-40DA-9400-F490F751B21E",
        "currentReviewLevel": {
            "reviewLevelId": "d2f957de-83e8-45a6-a384-458603727fc7",
            "type": "Initial",
            "status": "Initial",
            "reviewerDateAssigned": "2016-07-20",
            "reviewerDateDue": "2016-07-28",
            "reviewLocationName": "Denver QAD",
            "dateRequestSentToLender": "2016-07-20",
            "dateResponseDueFromLender": "2016-07-28"
        },
        "loanType": "Reverse (HECM)"
    },
    {
        "exceptionId": "456hreqqqqw3",
        "caseNumber": "351-3237642",
        "borrowerName": "Free, Lela",
        "lenderName": "Wells Fargo",
        "selectionReasonCode": "SRcvbn",
        "selectionReason": "Self-Report",
        "riskScore": 48,
        "exceptionTypeCode": "BATCH_ASSIGNMENT",
        "exceptionType": "Batch Assignment",
        "daysOnList": 3
    },
    {
        "exceptionId": "8765hwerthfwer",
        "caseNumber": "351-60225947",
        "borrowerName": "Crowder, Odis",
        "lenderName": "Chase",
        "selectionReasonCode": "SRwert",
        "selectionReason": "FHA Manual",
        "riskScore": 40,
        "exceptionTypeCode": "BATCH_DISTRIBUTION",
        "exceptionType": "Batch Distribution",
        "daysOnList": 1,
        "reviewId": "F7F2B500-A743-40DA-9400-F490F751B21E"
    },
    {
        "exceptionId": "45erwvqewr6",
        "caseNumber": "351-3376308",
        "borrowerName": "Ruckman, Bernita",
        "lenderName": "Douglas County Bank",
        "selectionReasonCode": "SRwert",
        "selectionReason": "FHA Manual",
        "riskScore": 70,
        "exceptionTypeCode": "BINDER_REQUEST_ERROR",
        "exceptionType": "Binder Request Error",
        "daysOnList": 1,
        "reviewId": "F7F2B500-A743-40DA-9400-F490F751B21E",
        "currentReviewLevel": {
            "reviewLevelId": "d2f957de-83e8-45a6-a384-458603727fc7",
            "type": "Initial",
            "status": "Initial",
            "reviewerDateAssigned": "2016-07-20",
            "reviewerDateDue": "2016-07-28",
            "reviewLocationName": "Denver QAD",
            "dateRequestSentToLender": "2016-07-20",
            "dateResponseDueFromLender": "2016-07-28"
        },
        "loanType": "Reverse (HECM)"
    },
    {
        "exceptionId": "456",
        "caseNumber": "351-9393830",
        "borrowerName": "Hartsoe, Noe",
        "lenderName": "1st Bank",
        "selectionReasonCode": "SRtyui",
        "selectionReason": "Early Claim",
        "riskScore": 21,
        "exceptionTypeCode": "VETTING_ACKNOWLEDGEMENT",
        "exceptionType": "Vetting Acknowledgement",
        "daysOnList": 1,
        "reviewId": "F7F2B500-A743-40DA-9400-F490F751B21E",
        "currentReviewLevel": {
            "reviewLevelId": "d2f957de-83e8-45a6-a384-458603727fc7",
            "type": "Initial",
            "status": "Initial",
            "reviewerDateAssigned": "2016-07-20",
            "reviewerDateDue": "2016-07-28",
            "reviewLocationName": "Denver QAD",
            "dateRequestSentToLender": "2016-07-20",
            "dateResponseDueFromLender": "2016-07-28"
        },
        "loanType": "Reverse (HECM)"
    },
    {
        "exceptionId": "234zest",
        "caseNumber": "351-5198201",
        "borrowerName": "McGee, Chip",
        "lenderName": "Wells Fargo",
        "selectionReasonCode": "SRxcvb",
        "selectionReason": "Lender Monit",
        "riskScore": 28,
        "exceptionTypeCode": "HQ_ESCALATION",
        "exceptionType": "HQ Escalation",
        "daysOnList": 6,
        "reviewId": "F7F2B500-A743-40DA-9400-F490F751B21E",
        "currentReviewLevel": {
            "reviewLevelId": "d2f957de-83e8-45a6-a384-458603727fc7",
            "type": "Initial",
            "status": "Initial",
            "reviewerDateAssigned": "2016-07-20",
            "reviewerDateDue": "2016-07-28",
            "reviewLocationName": "Denver QAD",
            "dateRequestSentToLender": "2016-07-20",
            "dateResponseDueFromLender": "2016-07-28"
        },
        "loanType": "Reverse (HECM)"
    }
]
