=== rarrington3/LRS/raml/api/v1/reviewers/reviewer-lite-schema.json
{
    "id": "http://LRS/ReviewerLite",
    "type": "object",
    "$schema": "http://json-schema.org/draft-03/schema",
    "required": [
        "reviewerId",
        "hudId",
        "nameFirst",
        "nameLast",
        "remainingCapacity",
        "locationId",
        "reportsTo"
    ],
    "additionalProperties": true,
    "properties": {
        "reviewerId": {
            "description": "The identifier of the object",
            "type": "string"
        },
        "hudId": {
            "description": "The login identifier of the reviewer; the user's HID.",
            "type": "string"
        },
        "nameFirst": {
            "description": "The forename of the reviewer.",
            "type": "string"
        },
        "nameLast": {
            "description": "The family name of the reviewer.",
            "type": "string"
        },
        "remainingCapacity": {
            "description": "The remaining number of reviews the reviewer can have assigned to them.",
            "type": "integer"
        },
        "locationId": {
            "description": "The ID of the geographical location where the reviewer does the review.",
            "type": "string"
        },
        "reportsTo": {
            "description": "The ID of the person who the reviewer reports to.",
            "type": "string"
        },
        "statusCode": {
            "description": "Status of the user; whether they are active (A), inactive (I), or terminated (T).",
            "type": "string"
        }
    }
}

=== rarrington3/LRS/raml/api/v1/reviewers/reviewers-lite-hq-collection-example.json
[
    {
        "reviewerId": "6037FDC9-5910-45F2-8059-8F0759B8DC58",
        "hudId": "HTH006",
        "nameFirst": "HDQTR",
        "nameLast": "LRS TEST 6",
        "remainingCapacity": 20,
        "locationId": "C2844126-716F-449A-B152-C891948888FA",
        "reportsTo": "",
        "statusCode": "A"
    },
    {
        "reviewerId": "6037FDC9-5910-45F2-8059-8F0759B8DC58",
        "hudId": "HTH007",
        "nameFirst": "HDQTR",
        "nameLast": "LRS TEST 7",
        "remainingCapacity": 20,
        "locationId": "C2844126-716F-449A-B152-C891948888FA",
        "reportsTo": "6037FDC9-5910-45F2-8059-8F0759B8DC58",
        "statusCode": "A"
    },
    {
        "reviewerId": "6037FDC9-5910-45F2-8059-8F0759B8DC58",
        "hudId": "HTH008",
        "nameFirst": "HDQTR",
        "nameLast": "LRS TEST 8",
        "remainingCapacity": 20,
        "locationId": "C2844126-716F-449A-B152-C891948888FA",
        "reportsTo": "6037FDC9-5910-45F2-8059-8F0759B8DC58",
        "statusCode": "A"
    }
]

=== rarrington3/LRS/raml/api/v1/reviewers/reviewers-lite-example.json
[
    {
        "reviewerId": "6037FDC9-5910-45F2-8059-8F0759B8DC58",
        "hudId": "HLRS01",
        "nameFirst": "John",
        "nameLast": "Doe",
        "remainingCapacity": 20,
        "locationId": "56F8FF8E-A7EF-40BE-B893-4D6FB57CE298",
        "reportsTo": "",
        "statusCode": "A"
    },
    {
        "reviewerId": "84807699-C805-4C76-9A89-76A026ADEE93",
        "hudId": "HLRS02",
        "nameFirst": "Jane",
        "nameLast": "Doe",
        "remainingCapacity": 20,
        "locationId": "56F8FF8E-A7EF-40BE-B893-4D6FB57CE298",
        "reportsTo": "6037FDC9-5910-45F2-8059-8F0759B8DC58",
        "statusCode": "A"
    },
    {
        "reviewerId": "F543D67C-68B9-44E0-91A7-F80326BD0EEA",
        "hudId": "HLRS03",
        "nameFirst": "Joh",
        "nameLast": "Smith",
        "remainingCapacity": 20,
        "locationId": "56F8FF8E-A7EF-40BE-B893-4D6FB57CE298",
        "reportsTo": "6037FDC9-5910-45F2-8059-8F0759B8DC58",
        "statusCode": "A"
    },
    {
        "reviewerId": "60188AB9-FD49-47A7-A59D-30592CB89C79",
        "hudId": "HLRS04",
        "nameFirst": "Jane",
        "nameLast": "Smith",
        "remainingCapacity": 20,
        "locationId": "56F8FF8E-A7EF-40BE-B893-4D6FB57CE298",
        "reportsTo": "6037FDC9-5910-45F2-8059-8F0759B8DC58",
        "statusCode": "A"
    }
]
