=== rarrington3/LRS/raml/api/v1/currentuser/currentuser-schema.json
{
    "id": "http://LRS/CurrentUser",
    "type": "object",
    "$schema": "http://json-schema.org/draft-03/schema",
    "additionalProperties": false,
    "properties": {
        "personnelId": {
            "description": "LRS-specific unique identifier for the current user if they are HUD personnel",
            "type": "string"
        },
        "hudId": {
            "description": "The login identifier of the user; the user's HID.",
            "type": "string"
        },
        "authorities": {
            "description": "A collection of this user's access rights.",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "firstName": {
            "description": "The first name of the current user.",
            "type": "string"
        },
        "lastName": {
            "description": "The last name of the current user.",
            "type": "string"
        },
        "lender": {
            "description": "An object containing information about the lender this user is associated with.",
            "$ref": "LiteLender"
        },
        "locationId": {
            "description": "Default location of user.",
            "type": "string"
        },
        "selectionReasonSkillCodes": {
            "description": "Collection of selection reason skill codes",
            "type": "array",
            "items": {
                "type": "string"
            }            
        },
        "reviewTypeSkillCodes": {
            "description": "Collection of selection review type skill codes",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "productTypeSkillCodes": {
            "description": "Collection of product type skill codes",
            "type": "array",
            "items": {
                "type": "string"
            }            
        },
        "reviewLevelSkillCodes": {
            "description": "Collection of selection review level skill codes",
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    }
}

=== rarrington3/LRS/raml/api/v1/currentuser/currentuser-example.json
{
    "personnelId": "current-user-id-asdf-1234",
    "hudId": "HLRS02",
    "authorities": [
        "ROLE_REVIEWER",
        "ROLE_PROGRAM_ASSISTANT",
        "ROLE_REVIEW_LOCATION_ADMIN",
        "ROLE_HQ_ADMIN",
        "ROLE_INDEMNIFIER",
        "ROLE_RESPONSE_COORDINATOR",
        "ROLE_LRS_READ_ONLY"
    ],
    "firstName": "Francis",
    "lastName": "Crozier",
    "lender": {
        "lenderId": "20063",
        "name": "First Security National Bank"
    },
    "locationId": "C2844126-716F-449A-B152-C891948888FA",
    "selectionReasonSkillCodes": ["TEST_CASE", "LENDER_MONITORING"],
    "reviewTypeSkillCodes": ["C"],
    "productTypeSkillCodes": [ "H"],
    "reviewLevelSkillCodes": ["ESCL", "FRCE", "INIT", "HQES", "INDM", "MITG"]
}
