=== rarrington3/LRS/raml/api/v1/admin/email-template-version.schema.json
{
    "id": "http://LRS/EmailTemplateVersion",
    "type": "object",
    "$schema": "http://json-schema.org/draft-03/schema",
    "required": [
        "emailName",
        "emailCategory",
        "version",
        "description",
        "lastModifiedDate",
        "lastModifiedBy",
        "activationDate",
        "id",
        "subject",
        "copy",
        "isActive",
        "documentVariables"
    ],
    "properties": {
        "emailName": {
            "description": "The name of the email this template belongs to.",
            "type": "string"
        },
        "emailCategory": {
            "description": "The category name of this email template version. Should hint at what this email is used for.",
            "type": "string"
        },
        "version": {
            "description": "An incremented counter of the templates created for this email.",
            "type": "integer"
        },
        "description": {
            "description": "A human readable description of this email template. Private to HUD.",
            "type": "string"
        },
        "lastModifiedDate": {
            "description": "The date that this template was last modified.",
            "type": "string",
            "format": "date"
        },
        "lastModifiedBy": {
            "description": "The name of who had last modified this email template.",
            "type": "string"
        },
        "activationDate": {
            "description": "The date that this template was activated.",
            "type": "string",
            "format": "date"
        },
        "isActive": {
            "description": "State of this email template version.",
            "type": "boolean"
        },
        "id": {
            "description": "A unique identifier of this Email Template.",
            "type": "string"
        },
        "subject": {
            "description": "The text that will render into the subject of this email.",
            "type": "string"
        },
        "copy": {
            "description": "The text that will render into the body of this email.",
            "type": "string"
        },
        "documentVariables": {
            "description": "A collection of variables that can be rendered into the template.",
            "type": "array",
            "items": {
                "$ref": "NameValuePair"
            }
        }
    }
}

=== rarrington3/LRS/raml/api/v1/admin/get-email-template.example.json
{
    "emailName": "Initial version",
    "emailCategory": "Mitigation Email",
    "version": 1,
    "description": "This is the initial version that can be used for mitigation email. By the way this is a description only to be seen when editing the email template version. Thanks!",
    "lastModifiedDate": "2016-07-28",
    "activationDate": "2016-07-28",
    "lastModifiedBy": "Justin Burch",
    "id": "a1a48fdd-ee56-4a93-938f-08f17f1ad417",
    "subject": "Re: Loan Defects for %LoanNumber%",
    "copy": "asdf \nasdf \n\nasdf\nasdf",
    "isActive": false,
    "documentVariables": [
        {
            "name": "Recipient",
            "value": "John Doe"
        },
        {
            "name": "Sender",
            "value": "Jane Doe"
        },
        {
            "name": "Greeting",
            "value": "Hello!"
        },
        {
            "name": "Signature",
            "value": "Thanks so much!"
        }
    ]
}
