=== rarrington3/LRS/raml/api/v1/admin/qaModel.schema.json
{
    "id": "http://LRS/QaModel",
    "type": "object",
    "$schema": "http://json-schema.org/draft-03/schema",
    "required": [
        "name"
    ],
    "properties": {
        "qaModelId": {
            "description": "The id of the qa model.",
            "type": "string"
        },
        "name": {
            "description": "The name of the qa model.",
            "type": "string"
        },
        "description": {
            "description": "The description of the qa model.",
            "type": "string"
        },
        "version": {
            "description": "The version of the qa model.",
            "type": "integer"
        },
        "activeReviews": {
            "description": "The amount of active reviews for the qa model.",
            "type": "integer"
        },
        "completedReviews": {
            "description": "The amount of completed reviews for the qa model.",
            "type": "integer"
        },
        "isActive": {
            "description": "Whether the qa model is active.",
            "type": "boolean"
        },
        "isReadonly": {
            "description": "Whether the qa model is readonly.",
            "type": "boolean"
        },
        "createdDate": {
            "description": "The date to which the qa model was created.",
            "type": "string",
            "format": "date"
        },
        "modifiedDate": {
            "description": "The date to which the qa model was last modified.",
            "type": "string",
            "format": "date"
        },
        "activatedDate": {
            "description": "The date to which the qa model was activated.",
            "type": "string",
            "format": "date"
        },
        "modifiedBy": {
            "description": "The person to which the qa model was last modified.",
            "type": "string"
        },
        "statusCode": {
            "description": "Code for an enumerated condition. Either 'active', 'draft', or 'archived'.",
            "type": "string"
        },
        "status": {
            "description": "Description for an enumerated condition. Either 'active', 'draft', or 'archived'.",
            "type": "string"
        }
    }
}

=== rarrington3/LRS/raml/api/v1/admin/qaModelCollection.example.json
[
    {
        "qaModelId": "QM12",
        "name": "Upgrade 2017 copy",
        "description": "This is a change to address the specific issues surrounding the shortcomings found in the previous version of the model.",
        "version": 12,
        "activeReviews": 625,
        "completedReviews": 345,
        "isActive": true,
        "isReadonly": true,
        "createdDate": "2016-10-20",
        "modifiedDate": "2016-10-21",
        "activatedDate": "2016-10-21",
        "modifiedBy": "Justin Burch",
        "statusCode": "A",
        "status": "Active"
    },
    {
        "qaModelId": "QM11",
        "name": "Upgrade 2017",
        "description": "This is a change to address the specific issues surrounding the shortcomings found in the previous version of the model.",
        "version": 11,
        "activeReviews": 0,
        "completedReviews": 0,
        "isActive": false,
        "isReadonly": true,
        "createdDate": "2016-10-20",
        "modifiedDate": "2016-10-21",
        "activatedDate": "2016-10-21",
        "modifiedBy": "Justin Burch",
        "statusCode": "R",
        "status": "Archived"
    },
    {
        "qaModelId": "QM10",
        "name": "Live LRS Re-Launch",
        "description": "This is a change to address the specific issues surrounding the shortcomings found in the previous version of the model.",
        "version": 10,
        "activeReviews": 625,
        "completedReviews": 345,
        "isActive": false,
        "isReadonly": false,
        "createdDate": "2016-10-20",
        "modifiedDate": "2016-10-21",
        "activatedDate": "2016-10-21",
        "modifiedBy": "Justin Burch",
        "statusCode": "D",
        "status": "Draft"
    }
]

=== rarrington3/LRS/raml/api/v1/admin/qaModel.example.json
{
    "qaModelId": "QM12",
    "name": "Upgrade 2017 copy",
    "description": "This is a change to address the specific issues surrounding the shortcommings found in the previous version of the model.",
    "version": 12,
    "activeReviews": 625,
    "completedReviews": 345,
    "isActive": true,
    "isReadonly": true,
    "createdDate": "2016-10-20",
    "modifiedDate": "2016-10-21",
    "activatedDate": "2016-10-21",
    "modifiedBy": "Justin Burch",
    "statusCode": "D",
    "status": "Draft"
}
