=== rarrington3/LRS/raml/api/v1/config/config.schema.json
{
    "id": "http://LRS/Config",
    "type": "object",
    "$schema": "http://json-schema.org/draft-03/schema",
    "additionalProperties": false,
    "properties": {
        "lrsUiDev": {
            "description": "Determines if the application is running in dev mode.",
            "type": "boolean"
        },
        "microstrategyUrl": {
            "description": "Url for microstrategy",
            "type": "string"
        },
        "electronicCaseBinder": {
            "description": "Url for accessing ecase binder.  {caseNumber} in the string is a placeholder for inserting an actual case number",
            "type": "string"
        },
        "electronicAppraisal": {
            "description": "Url for eAppraisals.  {caseNumber} in the string is a placeholder for inserting an actual case number",
            "type": "string"
        },
        "totalScorecardEmulator": {
            "description": "Url for accessing TOTAL scorecard emulator.  {caseNumber} in the string is a placeholder for inserting an actual case number",
            "type": "string"
        },
        "totalScorecardEmulatorComparison": {
            "description": "Url for accessing TOTAL scorecard emulator comparison.  {caseNumber} in the string is a placeholder for inserting an actual case number",
            "type": "string"
        }
    }
}

=== rarrington3/LRS/raml/api/v1/config/config.example.json
{
    "lrsUiDev": true,
    "electronicCaseBinder": "https://hwvalwd1868.hud.gov/clas/html/f17eb-ev.cfm?CaseNumber={caseNumber}",
    "electronicAppraisal": "https://hwvalwd1868.hud.gov/clas/html/f17eaprsl.cfm?key={caseNumber}",
    "totalScorecardEmulator": "https://hwvalwd1868.hud.gov/clas/html/f17ausform.cfm?type=pop&case_no={caseNumber}",
    "totalScorecardEmulatorComparison": "https://hwvalwd1868.hud.gov/clas/html/f17ausform.cfm?type=pop&case_no={caseNumber}&comp_data=Y",
    "microstrategyUrl": "https://entptest.hud.gov/LrsDev/MicroStrategy"
}
