=== rarrington3/LRS/raml/api/v1/cases/caseactivity-schema.json
{
    "id": "http://LRS/CaseActivity",
    "type": "object",
    "$schema": "http://json-schema.org/draft-03/schema",
    "additionalProperties": true,
    "properties": {
        "reviewId": {
            "description": "The Review ID of a canceled, active, or completed review related to the case.",
            "type": "string"
        },
        "reviewReferenceId": {
            "description": "The Review reference ID of a canceled, active, or completed review related to the case.",
            "type": "string"
        },
        "reviewStatus": {
            "description": "The status description of the canceled, active, or completed review related to the case.",
            "type": "string"
        },
        "distributionDate": {
            "description": "The date if this selection was distributed.",
            "type": "string",
            "format": "date"
        },
        "receivedDate": {
            "description": "The date if the binder has been recieved for this selection.",
            "type": "string",
            "format": "date"
        },
        "requestedDate": {
            "description": "The date if the binder has been requested for this selection.",
            "type": "string",
            "format": "date"
        },
        "selectionDate": {
            "description": "The date that this selection was created.",
            "type": "string",
            "format": "date"
        },
        "selectionStatus": {
            "description": "The status of this selection. (e.g. Selected, Requested, Received, Distributed, Exception, Cancelled)",
            "type": "string"
        },
        "caseNumber": {
            "description": "The case number for the loan selection",
            "type": "string"
        }
    }
}

=== rarrington3/LRS/raml/api/v1/cases/caseactivity-example.json
{
    "reviewId": "7B5DEB70-F109-44CA-88E2-264842B6473F",
    "reviewReferenceId": "75159-2017-000010",
    "reviewStatus": "Assigned",
    "distributionDate": "2017-07-19 23:40:13.980",
    "receivedDate": "2017-07-22 09:10:20.980",
    "requestedDate": "2017-07-20 08:00:20.980",
    "selectionDate": "2017-07-19 23:40:13.980",
    "selectionStatus": "Received"
}
