=== rarrington3/LRS/raml/api/v1/jobs/job.schema.json
{
    "id": "http://LRS/Job",
    "type": "object",
    "$schema": "http://json-schema.org/draft-03/schema",
    "properties": {
        "jobId": {
            "description": "The identifier of the job",
            "type": "string"
        },
        "type": {
            "description": "AGGREGATION, BINDER_DELIVERY_CHECK, DISTRIBUTION, EARLY_CLAIM_SELECTION, EARLY_PAYMENT_DEFAULT_SELECTION, ENDORSEMENT_SELECTION, or NATIONAL_QC_SELECTION",
            "type": "string"
        },
        "status": {
            "description": "Pending, Completed, Cancelled",
            "type": "string"
        },
        "parameters": {
            "type": "array",
            "items": {
                "$ref": "JobParameter"
            }
        },
        "executions": {
            "type": "array",
            "items": {
                "$ref": "JobExecution"
            }
        }
    }
}

=== rarrington3/LRS/raml/api/v1/jobs/job-collection.example.json
[
    {
        "jobId": "ABC123",
        "type": "AGGREGATION",
        "status": "Pending",
        "parameters": [
            {
                "name": "OFFICIAL_DATE",
                "value": "2017-01-01"
            },
            {
                "name": "START_DATE",
                "value": "2017-01-01"
            },
            {
                "name": "END_DATE",
                "value": "2017-01-02"
            }
        ],
        "executions": []
    },
    {
        "jobId": "ABC567",
        "type": "DISTRIBUTION",
        "status": "Complete",
        "parameters": [
            {
                "name": "OFFICIAL_DATE",
                "value": "2017-01-01"
            },
            {
                "name": "START_DATE",
                "value": "2017-01-01"
            },
            {
                "name": "END_DATE",
                "value": "2017-01-02"
            }
        ],
        "executions": [
            {
                "serverName": "HAZRLADLRS02",
                "serverPriority": "10"
            }
        ]
    }
]
